### PR TITLE
Linux System Logs Documentation

### LINKED ISSUE #49: New Pack Docs: Linux System Logs
Documentation for Illuminate Linux System Logs pack

### PR DESCRIPTION
**Pull request by jordan-linden**
## Notes for Reviewers

- [ ] The commit history must be preserved - please use the rebase-merge or standard merge option instead of squash-merge
- [ ] Sync up with the author before merging

Closes #49

### CODE REVIEW

**Comment by jordan-linden** [comment]
Table information for the GIM section of the documentation
[linux_gim_table.xlsx](https://github.com/user-attachments/files/17048579/linux_gim_table.xlsx)

**Comment by jordan-linden** [comment]
Table information for the message fields section of the documentation
[linux_fields.xlsx](https://github.com/user-attachments/files/17048697/linux_fields.xlsx)

**Comment by jordan-linden** [comment]
@annie-zempel Please see above comments for the GIM categorization and message fields tables to be added into the doc file. The insertion points are indicated in the file.

**Comment by annie-zempel** [comment]
Minor changes. Looks great. Thanks!

**Pull request merged**
